# This is the network config written by 'subiquity'
network:
  ethernets:
    enp8s0:
      dhcp6: true
      dhcp4: false
      addresses:
        - 192.168.0.2/24
      routes:
        - to: default
          via: 192.168.0.1
      nameservers:
        addresses:
          - 208.67.222.222
          - 208.67.220.220
      match:
        macaddress: 00:23:5a:62:a1:28
      set-name: enp8s0
  version: 2
  renderer: networkd
