network:
  version: 2
  ethernets:
    NM-0d2ffb26-1abf-4d8b-9cd5-9102e1d8d645:
      renderer: NetworkManager
      match:
        name: "enp8s0"
        macaddress: "00:23:5A:62:A1:28"
      addresses:
      - "192.168.0.2/24"
      nameservers:
        addresses:
        - 208.67.222.222
        - 208.67.220.220
      gateway4: 192.168.0.1
      dhcp6: true
      ipv6-address-generation: "stable-privacy"
      wakeonlan: true
      networkmanager:
        uuid: "0d2ffb26-1abf-4d8b-9cd5-9102e1d8d645"
        name: "Ethernet connection 1"
        passthrough:
          connection.timestamp: "1785542109"
          ipv6.ip6-privacy: "-1"
          proxy._: ""
