network:
  version: 2
  wifis:
    NM-4fad11d7-12cc-43b4-848b-411c6e852f2b:
      renderer: NetworkManager
      match:
        name: "wlan0"
      addresses:
      - "192.168.0.2/24"
      nameservers:
        addresses:
        - 208.67.222.222
        - 208.67.220.220
      gateway4: 192.168.0.1
      dhcp6: true
      ipv6-address-generation: "stable-privacy"
      access-points:
        "Apto104_2.4G":
          auth:
            key-management: "psk"
            password: "Finotti104"
          networkmanager:
            uuid: "4fad11d7-12cc-43b4-848b-411c6e852f2b"
            name: "Apto104_2.4G"
            passthrough:
              connection.timestamp: "1785544034"
              ipv6.ip6-privacy: "-1"
              proxy._: ""
      networkmanager:
        uuid: "4fad11d7-12cc-43b4-848b-411c6e852f2b"
        name: "Apto104_2.4G"
