[General]
__userfile__=true
leave_confirmation=false

[Environment]
BROWSER=firefox
GTK_CSD=0
GTK_OVERLAY_SCROLLING=0
SAL_USE_VCLPLUGIN=qt6
TERM=qterminal
XCURSOR_SIZE=48

[Mouse]
cursor_size=48
cursor_theme=breeze_cursors
