media_dir=V,/mnt/shared/filmes
media_dir=V,/mnt/shared/series
media_dir=P,/mnt/shared/series/Gatas
db_dir=/var/cache/minidlna
log_dir=/var/log/minidlna
root_container=PV
port=8200
friendly_name=DELL
album_art_names=Cover.jpeg/Folder.jpeg
