# Print my public IP
alias myip='curl ipinfo.io/ip && echo'

# Connect into a Clound
alias connect_funchal='qterminal -e ssh -i ~/.ssh/id_rsa.old lls@funchal.lls.net.br &'
alias connect_app='qterminal -e ssh -i ~/.ssh/id_rsa lls@app.lls.net.br &'

# Tomcat
alias tomcat-status='clear; sudo service tomcat9 status'
alias tomcat-start='sudo service tomcat9 start; tomcat-status'
alias tomcat-stop='sudo service tomcat9 stop; tomcat-status'
alias tomcat-restart='tomcat-stop; tomcat-start'
alias tomcat-log='geany /var/lib/tomcat9/logs/*.log &'

# MariaDB
alias maria-status='clear; sudo service mariadb status'
alias maria-start='sudo service mariadb start; maria-status'
alias maria-stop='sudo service mariadb stop; maria-status'
alias maria-restart='maria-stop; maria-start'
alias maria-log='geany /var/lib/mysql/error.log &'

# Iptables
alias iptables-status='clear; sudo service netfilter-persistent status'
alias iptables-start='sudo service netfilter-persistent start; iptables-status'
alias iptables-stop='sudo service netfilter-persistent stop; iptables-status'
alias iptables-restart='iptables-stop; iptables-start'
alias iptables-log='cat /var/log/syslog | grep netfilter | tail > /tmp/iptables.log && geany /tmp/iptables.log &'

# LLS
alias lls-status='tomcat-status; maria-status; iptables-status'
alias lls-start='tomcat-start; maria-start; iptables-start'
alias lls-stop='tomcat-stop; maria-stop; iptables-stop'
alias lls-restart='tomcat-restart; maria-restart; iptables-restart'

lls-log() {
	maria-log
	tomcat-log
	iptables-log
}

# Open a Terminal
alias terminal='terminal.sh gnome'

# Get a Zip GitHub Repository
alias git_zip_lls-src='cd ~; curl -L https://github.com/lls-ws/lls-src/archive/master.zip --output ~/.lls-src/lls-src-$(date +%F).zip; ls -al ~/.lls-src/lls-src-$(date +%F).zip'

# Get a GitHub Repository
alias git_clone_dataflex='cd ~; git clone https://github.com/lls-ws/dataflex.git; ls'
alias git_clone_desktop='cd ~; git clone https://github.com/lls-ws/desktop.git; ls'
alias git_clone_cloud='cd ~; git clone https://github.com/lls-ws/cloud.git; ls'
alias git_clone_lls-src='cd ~; git clone https://github.com/lls-ws/lls-src.git; git_zip_lls-src; ls'

# Update a GitHub Repository
alias git_upload_desktop='clear; cd ~/desktop; sudo ~/cloud/bin/git_conf.sh remote desktop; cd ~'
alias git_upload_cloud='clear; cd ~/cloud; sudo ~/cloud/bin/git_conf.sh remote cloud; cd ~'
alias git_upload_lls-src='clear; cd ~/lls-src; sudo ~/cloud/bin/git_conf.sh remote lls-src; cd ~'

# Backup a user profile
alias backup_user='clear; cd ~/desktop; bash ~/desktop/bin/user_config.sh backup; cd ~'

# Comands for Disable Services
alias disable-tomcat='sudo systemctl disable tomcat9.service'
alias disable-maria='sudo systemctl disable mariadb.service'
alias disable-iptables='sudo systemctl disable netfilter-persistent.service'
alias disable-cups='sudo systemctl disable cups.service'
alias disable-cron='sudo systemctl disable cron.service'
alias disable-snapd='sudo systemctl disable snapd.service'
alias disable-cups-browsed='sudo systemctl disable cups-browsed.service'
alias show-service='ls /etc/systemd/system/multi-user.target.wants'

# Comand for Only Upgrade Packages
alias upgrade='clear; sudo apt --only-upgrade -y install '

# Comand for Upgrade Packages
alias update='clear; sudo apt update && sudo apt -y upgrade && sudo apt -y autoremove && sudo apt list --upgradable'
alias version='uname -vr'

rmdir 'Área de trabalho' 'Imagens' 'Downloads' 'Documentos' 'Modelos' 'Músicas' 'Público' 'Vídeos' 2> /dev/null

rmdir 'Documents' 'Desktop' 'Music' 'Public' 'Videos' 'Pictures' 'Templates' 2> /dev/null

rm -rf 'Área de trabalho' 'Desktop' '.cache' '.dosbox' '.gnome' '.local' 'snap' 2> /dev/null
rm -f '.fehbg' 2> /dev/null
ls
