# Print my public IP
alias myip='curl ipinfo.io/ip && echo'

# Comands for Transmission
alias t-start='sudo service transmission-daemon start'
alias t-stop='sudo service transmission-daemon stop'
alias t-status='sudo service transmission-daemon status'
alias t-reload='sudo service transmission-daemon reload'
alias t-list='transmission-remote -n 'transmission:transmission' -l'
alias t-basicstats='transmission-remote -n 'transmission:transmission' -st'
alias t-fullstats='transmission-remote -n 'transmission:transmission' -si'

# Record a Stream Radio
alias record='sudo stream_record.sh uturn'

# Change Video Brightness
alias change_brightness='sudo change_brightness.sh'

# Connect into a Clound
alias cloud_connect='sudo cloud_connect.sh'

# Get Wifi Password
alias crack='sudo crack.sh'

# Open a Terminal
alias terminal='terminal.sh'

# Get a GitHub Repository
alias git_clone_dataflex='cd ~; git clone https://github.com/lls-ws/dataflex.git; ls'
alias git_clone_desktop='cd ~; git clone https://github.com/lls-ws/desktop.git; ls'
alias git_clone_cloud='cd ~; git clone https://github.com/lls-ws/cloud.git; ls'

# Update a GitHub Repository
alias git_upload_desktop='cd ~/desktop; sudo ~/cloud/bin/git_conf.sh remote desktop; cd ~'
alias git_upload_cloud='cd ~/cloud; sudo ~/cloud/bin/git_conf.sh remote cloud; cd ~'

# Backup a user profile
alias backup_user='cd ~/desktop; bash ~/desktop/bin/user_config.sh backup; cd ~'

rmdir 'Área de Trabalho' 'Música' 'Público' 'Vídeos' 2> /dev/null
rmdir 'Imagens' 'Downloads' 'Documentos' 2> /dev/null

rm -r '.cache' '.dosbox' '.gnome' '.local' 'snap' 2> /dev/null
rm '.fehbg' 2> /dev/null
