# Print my public IP
alias myip='curl ipinfo.io/ip && echo'

# Comands for Transmission
alias t-start='sudo service transmission-daemon start'
alias t-stop='sudo service transmission-daemon stop'
alias t-status='sudo service transmission-daemon status'
alias t-reload='sudo service transmission-daemon reload'
alias t-list='transmission-remote -n 'transmission:transmission' -l'
alias t-basicstats='transmission-remote -n 'transmission:transmission' -st'
alias t-fullstats='transmission-remote -n 'transmission:transmission' -si'

# Record a Stream Radio
alias record='sudo stream_record.sh uturn'

# Change Video Brightness
alias change_brightness='sudo change_brightness.sh'

# Connect into a Clound
alias cloud_connect='gnome-terminal --tab --title Cloud -- ssh -i ~/.ssh/id_rsa lls@funchal.lls.net.br'

# Get Wifi Password
alias crack='sudo crack.sh'

# Open a Terminal
alias terminal='terminal.sh gnome'

# Get a GitHub Repository
alias git_clone_dataflex='cd ~; git clone https://github.com/lls-ws/dataflex.git; ls'
alias git_clone_desktop='cd ~; git clone https://github.com/lls-ws/desktop.git; ls'
alias git_clone_cloud='cd ~; git clone https://github.com/lls-ws/cloud.git; ls'
alias git_clone_lls-src='cd ~; git clone https://github.com/lls-ws/lls-src.git; ls'

# Update a GitHub Repository
alias git_upload_desktop='clear; cd ~/desktop; sudo ~/cloud/bin/git_conf.sh remote desktop; cd ~'
alias git_upload_cloud='clear; cd ~/cloud; sudo ~/cloud/bin/git_conf.sh remote cloud; cd ~'
alias git_upload_lls-src='clear; cd ~/lls-src; sudo ~/cloud/bin/git_conf.sh remote lls-src; cd ~'

# Backup a user profile
alias backup_user='clear; cd ~/desktop; bash ~/desktop/bin/user_config.sh backup; cd ~'

# Comands for MariaDB
alias maria-start='sudo service mariadb start'
alias maria-stop='sudo service mariadb stop'
alias maria-status='sudo service mariadb status'
alias maria-restart='sudo service mariadb restart'

# Comands for Tomcat
alias tom-start='sudo service tomcat9 start'
alias tom-stop='sudo service tomcat9 stop'
alias tom-status='sudo service tomcat9 status'
alias tom-restart='sudo service tomcat9 restart'

# Comands for Disable Services
alias disable-snapd='sudo systemctl disable snapd.service'
alias disable-cups='sudo systemctl disable cups.service'
alias disable-cron='sudo systemctl disable cron.service'
alias disable-cups-browsed='sudo systemctl disable cups-browsed.service'
alias show-service='ls /etc/systemd/system/multi-user.target.wants'

rmdir 'Área de Trabalho' 'Música' 'Público' 'Vídeos' 2> /dev/null
rmdir 'Imagens' 'Downloads' 'Documentos' 2> /dev/null

rm -rf '.cache' '.dosbox' '.gnome' '.local' 'snap' 2> /dev/null
rm -f '.fehbg' 2> /dev/null
ls
