#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Lubuntu (Desktop)" --class lubuntu --class os {
    insmod part_msdos
    insmod ext2
    search --no-floppy --fs-uuid --set=root COPIE_O_UUID_AQUI
    linux /vmlinuz root=UUID=COPIE_O_UUID_AQUI ro quiet splash
    initrd /initrd.img
}
