#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Lubuntu (Desktop /dev/sda3)" --class lubuntu {
    insmod part_gpt
    insmod ext2
    set root='hd0,gpt3'
    configfile /boot/grub/grub.cfg
}
