#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# UUID=9c804a77-aa7b-4df3-b110-1482947d87a4
menuentry "Lubuntu (Desktop /dev/sda2)" --class lubuntu --class os {
    insmod part_gpt
    insmod ext2
    search --no-floppy --fs-uuid --set=root 9c804a77-aa7b-4df3-b110-1482947d87a4
    configfile /boot/grub/grub.cfg
}
